name: Sync HomeNet Inventory

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch:     

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch CSV from FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: skipster-inventory.site
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./
          server-dir: ./
          state-name: .ftp-deploy-sync-state.json
          dangerous-clean-slate: false

      - name: Force Update Inventory
        run: |
          git config --global user.name 'Inventory Bot'
          git config --global user.email 'bot@skipster.ai'
          git add .
          git commit -m "Force refresh from HomeNet" || echo "No changes to save"
          git push
